name: test
on: push
jobs:
  make-lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install, build
        run: make install
        
      - name: launch tests
        run: make test