name: test and code coverage
on: push
jobs:
  make-test:
    name: test code
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install, build
        run: make install
        env:
          CI: true

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage 
          debug: true
      
      - name: tests
        run: make test 