name: test and code coverage
on: push
jobs:
  make-lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install, build
        run: make install

      - name: launch test-coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE }}
        run: make test-coverage
      
      - name: tests
        run: make test 