name: test and code coverage
on: push
jobs:
  make-lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install, build
        run: make install

      - name: launch tests
        env: CC_TEST_REPORTER_ID: d2703ab37114d7bf0c2c470448a12299e909316e584862e844fb1dc163d997fc
        run: make test